nelmio_api_doc:
    areas:
        path_patterns: # an array of regexps
            - ^/api
    documentation:
        info:
            title: ApiTest
            description: Un acercamiento hacia una api Rest de con Documentacion de calidad y vision de microservicios
            version: 0.0.1