app.swagger_ui:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /api/doc

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

app:
    resource: '@AppBundle/Controller/'
    type: annotation


user:
    type: rest
    prefix: /api
    resource: app.user_controller



