#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app:
    resource: '@AppBundle/Controller/'
    type: annotation


user:
    type: rest
    prefix: /api
    resource: app.user_controller