imports:
    - { resource: twitter.conf.yml }

parameters:
    # Guzzle classes
    class.guzzle.client: GuzzleHttp\Client
    class.guzzle.emitter: GuzzleHttp\Event\Emitter
    class.guzzle.oauthplugin: GuzzleHttp\Subscriber\Oauth\Oauth1

services:
    # MessageService definition, created by a Factory
    app.twitter_message_service:
        class:   AppBundle\Service\TwitterMessageService
        factory: ['AppBundle\Factory\MessageHandlerStaticFactory', createTwitterMessageService]
        arguments: ['@service_container']
        public: true
    # MessageService definition, created by a Factory
    app.message_handler:
        class:   AppBundle\Command\GetMessagesHandler
        arguments: ['@app.twitter_message_service','@cache.app.messages']
        tags:
            - { name: tactician.handler, command: AppBundle\Command\GetMessagesCommand }
        public: true
    # Controller as a service for FOSRest routes
    app.user_controller:
        class: AppBundle\Controller\UserController
        arguments:
            - '@tactician.commandbus'
    # Guzzle twitter emitter
    guzzle.twitter.emitter:
        class: %class.guzzle.emitter%
        calls:
            - [attach, ['@guzzle.twitter.oauthplugin']]
    # Guzzle twitter client
    guzzle.twitter.client:
        class: %class.guzzle.client%
        arguments:
            - {base_url: ['%twitter.baseurl%', {version: '%twitter.version%'}], defaults: {auth: 'oauth'}, emitter: '@guzzle.twitter.emitter'}
    # Guzzle twitter oauth
    guzzle.twitter.oauthplugin:
        class: %class.guzzle.oauthplugin%
        arguments: ['%twitter.config%']
